### ISSUE TITLE
Not possible to catch an exception in case of a sudden user exit.

### ISSUE THREAD

**Issue by MrHag** [uhm0311/EngineIOSharp#2]
I have an issue when i try to catch exception that throwed in **SocketIOSocket.Emit** method.
That my method wrapper:
```csharp
public static void EmitTo(this SocketIOServer server, SocketIOSocket socket, string header, object body)
        {
            try
            {
                socket.Emit(header, body);
            }
            catch (Exception ex)
            {
#if DEBUG
                Program.LogService.Log(ex);
#endif
            }
        }
```
In case when user exited before emitted to him I getting uncaught Exception.
```
EngineIOSharp.Server.Client.EngineIOSocket : EngineIOSharp.Common.EngineIOException: Socket closed.
System.InvalidOperationException: The current state of the connection is not Open.
   at WebSocketSharp.WebSocket.Send(String data)
   at EngineIOSharp.Server.Client.Transport.EngineIOWebSocket.<>c__DisplayClass7_0.<Send>b__0(Object _)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
I think that need to globally change method ThreadPool.QueueUserWorkItem to Task.Run. That's will allow to catch such exceptions.

**Comment by uhm0311** [comment]
Thank you for reporting. Can you please send me codes to reproduce this exception?

Note: according to this [question](https://stackoverflow.com/questions/32067034/how-to-handle-task-run-exception), Task.Run also can not catch exceptions without await. I think I should use try-catch inside of it, not outside.

**Comment by MrHag** [comment]
> Thank you for reporting. Can you please send me codes to reproduce this exception?

I cannot artificially reproduce this bug, but it's happening in my project https://github.com/MrHag/Keyboardchat/tree/Csharp, that used this library, where I filling filelds and click login. After this i immediately close browser page and get this exception.

Note: Class that wrap this method: https://github.com/MrHag/Keyboardchat/blob/Csharp/Server/Extensions/SocketIOServerExtension.cs

**Comment by uhm0311** [comment]
I've updated [SocketIOSharp to v2.0.1](https://www.nuget.org/packages/SocketIOSharp/2.0.1). It would fix this bug. Can you test it after update?

**Comment by MrHag** [comment]
>Can you test it after update?

Yeah. Bug fixed. Thank you.
