### ISSUE TITLE
Stackover flow exception

### ISSUE THREAD

**Issue by shlom29** [uhm0311/EngineIOSharp#4]
Hi,
in the file:
https://github.com/uhm0311/EngineIOSharp/blob/master/EngineIOSharp/Client/Transport/EngineIOPolling.cs
Poll method is calling to Request method
Request method is calling HandleResponse method
HandleResponse method is calling to Poll

Get into this scenario after long run (few hour), but it is possible.

**Comment by uhm0311** [comment]
LOL, I don't know why I did that. Thanks for reporting.
